baseURL = 'https://blog.stefanovskyi.com'
languageCode = 'en-us'
title = 'Oleksandr Stefanovskyi Blog'
theme = "cactus"
[params]

  description = "[Strategic Technology Partner](https://stefanovskyi.com/) who aligns tech plans with business goals and guides projects from first sketch to launch. Lately, I have led work that puts Generative AI into production training domain-specific models, building prompt workflows, and setting up secure deployment rails. I still design and scale microservice systems, practice test-driven development, and keep both engineers and senior leaders on the same page."
  
  mainSectionTitle = "Blog posts:"
  
  showAllPostsOnHomePage = true

  colortheme = "dark" # dark, light, white, or classic
  # Main menu which appears below site header.

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/oleksandr-stefanovskyi/"
